### ISSUE TITLE
Puzzles: does it need to call delete to free memory for Qt3D?

### ISSUE THREAD

**Issue by chao-sun01io** [MASKOR/Qt3DPointcloudRenderer#7]
In class QPointcloudGeometryPrivate

```
class QPointcloudGeometryPrivate
{
public:
    QPointcloudGeometryPrivate()
        :m_vertexBuffer(NULL)
        ,m_colorBuffer(NULL)
        ,m_pointcloud(NULL)
        ,m_colorOffset(0)
        ,m_colorFormatUintRgba(false)
        ,m_colorAvailable(false)
    {}
    Qt3DRender::QBuffer *m_vertexBuffer;
    Qt3DRender::QBuffer *m_colorBuffer;
    QPointcloud *m_pointcloud;
    int m_colorOffset;
    bool m_colorFormatUintRgba;
    bool m_colorAvailable;
};
```
Will the memory of QBuffer s and QPointcloud be released automatically? I don't see any `delete` syntax so will they set a parent QObject implicitly?  thank you for your reply

**Comment by dabulla** [comment]
m_vertexBuffer and m_colorBuffer get a pointer to "this" (refering to QPointcloudGeometry) as a parent.
Both are set in the constructor:
`QPointcloudGeometry::QPointcloudGeometry(Qt3DCore::QNode *parent)
    :m_p(new QPointcloudGeometryPrivate)
{
    m_p->m_vertexBuffer = new Qt3DRender::QBuffer(Qt3DRender::QBuffer::VertexBuffer, this);
    m_p->m_colorBuffer = new Qt3DRender::QBuffer(Qt3DRender::QBuffer::VertexBuffer, this);
}`
GeometryPrivate is not the owner of of a QPointcloud, so it should never call new or delete for it (it's just a reference to internally navigate up to the pointcloud).
Only the pointers are initialized with NULL (it's not the the QObject parent). It's initialized with NULL because the code is in the non-private class.
I don't see a memory leak here, but feel free to test it and measure a little bit. A leak here would be terrific :).

**Comment by chao-sun01io** [comment]
@dabulla I seee...Thank you for your reply.
